export const TEAMFILTERS = [
    "angels",
    "astros",
    "athletics",
    "blue jays",
    "braves",
    "brewers",
    "cardinals",
    "cubs",
    "devil rays",
    "diamondbacks",
    "dodgers",
    "expos",
    "giants",
    "indians",
    "mariners",
    "marlins",
    "mets",
    "orioles",
    "padres",
    "phillies",
    "pirates",
    "rangers",
    "red sox",
    "reds",
    "rockies",
    "royals",
    "tigers",
    "twins",
    "white sox",
    "yankees"
]